excluded:
  - MinervaExample/Shared/Generated
  - Pods
  - Playground

blacklist_rules:
  # Swift type system doesn't allow wrapping the .map { $0 } easily
  - array_init
  # We like the shorthand 1-liners
  - conditional_returns_on_newline
  # Fix errors
  - cyclomatic_complexity
  # Sometimes we want this (our protos)
  - discouraged_optional_boolean
  # Apple overrides trigger this
  - discouraged_optional_collection
  # Doesn't work with PromiseKit methodName().then
  - empty_parentheses_with_trailing_closure
  # Fix warnings then enable
  - explicit_enum_raw_value
  # We like the shorthand without self.
  - explicit_self
  # We like the shorthand where the type is inferred
  - explicit_type_interface
  # Throws an errors
  - extension_access_modifier
  # Fix this then enable
  - file_types_order
  # Doesn't work with realm results queries where a filter needs to be first
  - first_where
  # Used to work around the poor swift generic type system
  - force_cast
  # This should be enabled, but there is a lot of cleanup required
  - force_unwrapping
  # This should be enabled, but there is a lot of cleanup required
  - function_parameter_count
  # Need to cleanup the notification names and set the min to 2
  - identifier_name
  # Lots of cleanup for non IBOutlets
  - implicitly_unwrapped_optional
  # We dont document
  - missing_docs
  # Fix the warnings then enable this
  - multiline_arguments_brackets
  # Fix the warnings then enable this
  - multiline_function_chains
  # We like extensions in the same file
  - no_grouping_extension
  # Weird limitation
  - notification_center_detachment
  # We need to use localized strings to support this
  - nslocalizedstring_key
  # We need to support localized strings
  - nslocalizedstring_require_bundle
  # We dont like literals
  - object_literal
  # Against swift style
  - prefixed_toplevel_constant
  # Remove the old watch code then enable this
  - prohibited_interface_builder
  # Quick is horrible
  - quick_discouraged_call
  # Quick is horrible
  - quick_discouraged_focused_test
  # Quick is horrible
  - quick_discouraged_pending_test
  # Turn on and fix readability
  - reduce_into
  # We are explicit with enum values
  - redundant_string_enum_value
  # Who would want this?
  - required_deinit
  # Turn on?
  - static_operator
  # Fix the warnings then enable this
  - strict_fileprivate
  # We dont use IB anymore
  - strong_iboutlet
  # Fix warnings and enable this
  - switch_case_on_newline
  # Have a better TODO policy then enable this
  - todo
  # Fix this then enable
  - type_contents_order
  # Overridding vars cause problems with this?
  - unused_setter_value
  # We don't use IB anymore
  - valid_ibinspectable
  # Don't like it
  - vertical_whitespace_between_cases
  # Don't like it
  - vertical_whitespace_closing_braces
  # Don't like it
  - vertical_whitespace_opening_braces
  # Who does this?
  - yoda_condition

whitelist_rules:
  - anyobject_protocol
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - empty_xctest_method
  - explicit_acl
  - explicit_init
  - explicit_top_level_acl
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - file_name
  - for_where
  - force_try
  - function_body_length
  - function_default_parameter_at_end
  - generic_type_name
  - identical_operands
  - implicit_getter
  - implicit_return
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_space_in_method_call
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message

closure_body_length:
  warning: 100
  error: 100

file_length:
  warning: 1000
  error: 1000

function_body_length:
  warning: 150
  error: 150

line_length:
  warning: 500
  error: 500

type_body_length:
  warning: 500
  error: 500
