source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

def minerva_pods
  pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'PromiseKit/CorePromise'
  pod 'RxSwift'
  pod 'SwiftProtobuf'
  pod 'SwipeCellKit'
end

target 'Minerva' do
  platform :ios, '11.0'
  minerva_pods
end

target 'MinervaExample' do
  platform :ios, '11.0'
  minerva_pods
end

target 'MinervaExampleTests' do
  platform :ios, '11.0'
  minerva_pods
end

target 'MinervaExampleUITests' do
  platform :ios, '11.0'
  minerva_pods
end
