# .slather.yml

coverage_service: cobertura_xml
xcodeproj: Minerva.xcodeproj
workspace: Minerva.xcworkspace
scheme: Minerva
ignore:
  - MinervaCatalog/*
  - MinervaExample/*
  - MinervaTests/*
  - Pods/*
