excluded:
  - MinervaExample/Generated
  - Pods

blacklist_rules:
  - array_init
  - conditional_returns_on_newline
  - cyclomatic_complexity
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_parentheses_with_trailing_closure
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_types_order
  - first_where
  - force_cast
  - force_unwrapping
  - function_parameter_count
  - identifier_name
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_arguments_brackets
  - multiline_function_chains
  - no_grouping_extension
  - notification_center_detachment
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - object_literal
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_string_enum_value
  - required_deinit
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - todo
  - trailing_closure
  - type_contents_order
  - unused_setter_value
  - valid_ibinspectable
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

whitelist_rules:
  - anyobject_protocol
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_top_level_acl
  - fallthrough
  - fatal_error_message
  - file_length
  - file_name
  - for_where
  - force_try
  - function_body_length
  - function_default_parameter_at_end
  - generic_type_name
  - identical_operands
  - implicit_getter
  - implicit_return
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_space_in_method_call
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message

closure_body_length:
  warning: 100
  error: 100

file_length:
  warning: 1000
  error: 1000

function_body_length:
  warning: 150
  error: 150

line_length:
  warning: 500
  error: 500

type_body_length:
  warning: 500
  error: 500
