osx_image: xcode11.2
language: swift
cache:
  bundler: true
  cocoapods: true
  directories:
    - Carthage
before_install:
  - brew update

jobs:
  include:
    - stage: Lint CocoaPod
      install:
        - brew outdated cocoapods || brew upgrade cocoapods
      script:
        - pod lib lint
    - stage: Test & Code Coverage
      install:
        - brew outdated cocoapods || brew upgrade cocoapods
        - brew install xcodegen
        - gem install slather
      script:
        - set -o pipefail && xcodebuild -workspace MinervaExample.xcworkspace -scheme MinervaExample -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2' build test | xcpretty
        - slather
        - bash <(curl -s https://codecov.io/bash)
